# Generated by Django 3.2.8 on 2021-12-29 16:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0003_player_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.URLField(blank=True, max_length=256, verbose_name='头像图片地址'),
        ),
        migrations.AlterField(
            model_name='player',
            name='score',
            field=models.IntegerField(default=1500, verbose_name='累计得分'),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.URLField(blank=True, max_length=256, verbose_name='头像图片地址')),
                ('text', models.TextField(blank=True, default='', verbose_name='留言内容')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2021, 12, 29, 16, 32, 46, 819674, tzinfo=utc), verbose_name='创建时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
        ),
    ]
