# Generated by Django 3.2.8 on 2021-12-30 01:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20211230_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='username',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='message',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 30, 1, 59, 8, 839444, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
