# Generated by Django 3.2.8 on 2021-12-30 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_message_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 30, 17, 56, 47, 539999), verbose_name='创建时间'),
        ),
    ]
