# Generated by Django 3.2.8 on 2021-12-31 03:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_message_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 31, 3, 34, 36, 619470, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
