# Generated by Django 3.2.8 on 2021-12-31 03:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_message_create_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='皮肤名')),
                ('imgSrc', models.URLField(blank=True, max_length=256, verbose_name='皮肤图片地址')),
                ('description', models.TextField(blank=True, default='', verbose_name='皮肤描述')),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 31, 3, 36, 56, 101142, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
